name: Create Release Files

on: 
  push:
    tags:
      - '*'

jobs:

  upload-release-files:
    runs-on: ubuntu-latest
    steps:
      - name: "zip files"
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: DGG_Everywhere/
          recursive: true
          dest: DGG_Everywhere.zip
      - uses: vimtor/action-zip@v1
        with:
          files: DGG_Everywhere_FF/
          recursive: false
          dest: DGG_Everywhere_FF.zip

      - uses: actions/checkout@v1
      - name: "find env"
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          zip -r pkg.zip *.md
          echo "$(openssl rand -hex 4)" > "random-name-$(openssl rand -hex 4).txt"
          echo "$(openssl rand -hex 4)" > "random-name-$(openssl rand -hex 4).txt"
      
      - name: "Create Pre-Release"
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} (draft)
          body: |
            Create Pre-release Files
          allowUpdates: true
          draft: true
          prerelease: true

      - name: "Uplad Files"
      - uses: xresloader/upload-to-github-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: DGG_Everywhere.zip;DGG_Everywhere_FF.zip
       
       
      
    
