name: Create Release Files

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: DGG_Everywhere/
          recursive: true
      - uses: vimtor/action-zip@v1
        with:
          files: DGG_Everywhere_FF/
          recursive: false
          dest: DGG_Everywhere_FF.zip
