name: Create Release Files

on: 
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: "Create Release Files"
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          zip -r DGG_Everywhere.zip DGG_Everywhere
          zip -r DGG_Everywhere_FF.zip DGG_Everywhere_FF
          echo "$(openssl rand -hex 4)" > "random-name-$(openssl rand -hex 4).txt"
          echo "$(openssl rand -hex 4)" > "random-name-$(openssl rand -hex 4).txt"

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "Create Release"
        id: create_release
        with:
          title: "Latest Development Build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest-dev"
          files: |
            DGG_Everywhere.zip
            DGG_Everywhere_FF.zip